name: Appium Android Emulator CI

on: push

jobs:
  appium-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install Appium & Drivers
      run: |
        npm install -g appium
        appium driver install uiautomator2

    - name: Install Android SDK & Emulator
      run: |
        export ANDROID_SDK_ROOT=$HOME/android-sdk
        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
        cd $ANDROID_SDK_ROOT/cmdline-tools
        curl -o tools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
        unzip -q tools.zip
        mv cmdline-tools latest

        export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH

        # Remove any previously cached system images
        rm -rf $ANDROID_SDK_ROOT/system-images/*

        yes | sdkmanager --licenses
        sdkmanager --install "platform-tools" \
                            "emulator" \
                            "platforms;android-30" \
                            "system-images;android-30;google_apis;x86_64"
      env:
        JAVA_HOME: ${{ env.JAVA_HOME }}

    - name: Create AVD (Pixel, x86_64)
      run: |
        export ANDROID_SDK_ROOT=$HOME/android-sdk
        export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
        echo "no" | avdmanager create avd -n emulator-5554 \
          -k "system-images;android-30;google_apis;x86_64" -d pixel

    - name: Start Emulator in Background
      run: |
        export ANDROID_SDK_ROOT=$HOME/android-sdk
        export PATH=$ANDROID_SDK_ROOT/emulator:$ANDROID_SDK_ROOT/platform-tools:$PATH

        nohup $ANDROID_SDK_ROOT/emulator/emulator -avd emulator-5554 \
          -no-audio -no-window -no-boot-anim -no-snapshot \
          -gpu swiftshader_indirect > /dev/null 2>&1 &
        sleep 5

    - name: Wait for Emulator to Boot (timeout 5 min)
      run: |
        export PATH=$HOME/android-sdk/platform-tools:$PATH
        adb wait-for-device

        timeout=300
        elapsed=0
        until [[ "$(adb shell getprop sys.boot_completed | tr -d '\r')" == "1" ]]; do
          if [[ $elapsed -ge $timeout ]]; then
            echo "Timeout: Emulator did not boot in $timeout seconds"
            adb -s emulator-5554 emu kill
            exit 1
          fi
          echo "  ➤ boot_completed = 0 (waiting...)"
          sleep 5
          elapsed=$((elapsed + 5))
        done

        echo "Emulator booted. Disabling animations..."
        adb shell settings put global window_animation_scale 0.0 || true
        adb shell settings put global transition_animation_scale 0.0 || true
        adb shell settings put global animator_duration_scale 0.0 || true

    - name: Start Appium Server
      run: |
        nohup appium --address 0.0.0.0 --port 4723 > appium.log 2>&1 &
        sleep 5
        echo "Appium server running at http://0.0.0.0:4723/wd/hub"

    - name: Run TestNG Tests
      run: mvn clean test -DsuiteXmlFile=testng.xml

    - name: Stop Emulator
      run: adb -s emulator-5554 emu kill || true

