name: Appium Manual Android Emulator

on: push

jobs:
  appium-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Set up Node.js for Appium
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install Appium and UiAutomator2 Driver
      run: |
        npm install -g appium
        appium driver install uiautomator2

    - name: Set up Android SDK and Emulator
      run: |
        yes | sdkmanager --licenses
        sdkmanager --install "platform-tools" \
                               "emulator" \
                               "platforms;android-30" \
                               "system-images;android-30;google_apis;x86_64"

    - name: Create AVD
      run: |
        echo "no" | avdmanager create avd -n emulator-5554 -k "system-images;android-30;google_apis;x86_64" -d pixel

    - name: Start Emulator
      run: |
        nohup $ANDROID_HOME/emulator/emulator -avd emulator-5554 -no-window -no-audio -gpu off > /dev/null 2>&1 &

    - name: Wait for Emulator to Boot
      run: |
        echo "Waiting for emulator to boot..."
        adb wait-for-device
        boot_completed=""
        until [[ "$boot_completed" == "1" ]]; do
          boot_completed=$(adb shell getprop sys.boot_completed | tr -d '\r')
          echo "  ➤ boot_completed = $boot_completed"
          sleep 5
        done
        echo "Emulator fully booted."

        echo "Disabling animations for test stability..."
        adb shell settings put global window_animation_scale 0.0 || true
        adb shell settings put global transition_animation_scale 0.0 || true
        adb shell settings put global animator_duration_scale 0.0 || true

    - name: Start Appium Server
      run: |
        nohup appium --address 0.0.0.0 --port 4723 > appium.log 2>&1 &
        sleep 5

    - name: Run TestNG Tests
      run: mvn clean test -DsuiteXmlFile=testng.xml

    - name: Stop Emulator
      run: adb -s emulator-5554 emu kill || true
