name: Android Emulator Boot Only

on: push

jobs:
  emulator-only:
    runs-on: macos-14

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Start Emulator
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: arm64-v8a
          profile: pixel_6
          disable-animations: true
          emulator-boot-timeout: 600
          script: |
            echo "✅ Emulator booted"
            adb devices
            DEVICE_ID=$(adb devices | grep emulator | awk '{print $1}')
            echo "Running emulator device: $DEVICE_ID"
            sleep 10
            echo "🛑 Stopping emulator..."
            adb -s "$DEVICE_ID" emu kill || echo "❌ Could not kill emulator (already shut down?)"
