name: Launch Android Emulator Only

on:
  workflow_dispatch:

jobs:
  launch-emulator:
    name: Boot Android Emulator
    runs-on: ubuntu-latest

    steps:
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Maven
        run: sudo apt-get install -y maven

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses and install emulator tools
        run: |
          yes | sdkmanager --licenses
          sdkmanager --install "platforms;android-30" "platform-tools" "emulator" "system-images;android-30;google_apis;x86_64"
          avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" --device "pixel_3" --force || true
          avdmanager list avd
          ls -la $HOME/.android/avd/
          ${ANDROID_SDK_ROOT}/emulator/emulator -avd test -no-window -no-audio -no-boot-anim -no-snapshot-save &
          sleep 5

      - name: Add ADB to PATH
        run: echo "${ANDROID_SDK_ROOT}/platform-tools" >> $GITHUB_PATH

      - name: Wait for Emulator to Fully Boot
        run: |
          echo "Waiting for emulator to stabilize..."
          adb wait-for-device
          boot_completed=""
          timeout=120
          elapsed=0
          until [[ "$boot_completed" == "1" || $elapsed -ge $timeout ]]; do
            boot_completed=$(adb shell getprop sys.boot_completed | tr -d '\r')
            sleep 2
            elapsed=$((elapsed + 2))
          done
          if [[ "$boot_completed" != "1" ]]; then
            echo "Emulator failed to boot in $timeout seconds"
            exit 1
          fi
          echo "Emulator booted."
