name: Launch Android Emulator on macOS

on: push

jobs:
  emulator:
    name: Start Android Emulator (macOS)
    runs-on: macos-latest

    steps:
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install and Start Emulator
        run: |
          yes | sdkmanager --licenses
          sdkmanager --install "platforms;android-30" "platform-tools" "emulator" "system-images;android-30;google_apis;x86_64"

          echo "Creating AVD..."
          echo no | avdmanager create avd -n pixel_3 -k "system-images;android-30;google_apis;x86_64" --device "pixel" --force

          echo "Starting emulator..."
          $ANDROID_HOME/emulator/emulator -avd pixel_3 -no-window -no-audio -no-boot-anim -gpu host &
          echo "Waiting for emulator to boot..."
          adb wait-for-device

          boot_completed=""
          retries=0
          max_retries=60
          until [[ "$boot_completed" == "1" || $retries -ge $max_retries ]]; do
            boot_completed=$(adb shell getprop sys.boot_completed | tr -d '\r')
            sleep 2
            ((retries++))
          done

          if [[ "$boot_completed" != "1" ]]; then
            echo "Emulator boot timeout."
            exit 1
          fi

          echo "Emulator is ready."
          echo "AVDs available:"
          avdmanager list avd
