name: Appium Android Emulator CI

on: push

jobs:
  test:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Launch Emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        target: google_apis
        arch: x86_64
        profile: pixel
        disable-animations: true
        emulator-boot-timeout: 600

    - name: Install Appium & Drivers
      run: |
        npm install -g appium
        appium driver install uiautomator2
        nohup appium --address 0.0.0.0 --port 4723 > appium.log 2>&1 &

    - name: Run TestNG Tests
      run: mvn clean test -DsuiteXmlFile=testng.xml
