
name: Android Emulator Test Run

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest  

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Launch Emulator and Run Instrumentation Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        target: google_apis
        arch: x86_64
        profile: Nexus 6
        disable-animations: true
        script: |
          echo "Waiting for emulator to boot..."
          adb wait-for-device
          echo "Running instrumentation tests..."
          ./gradlew connectedDebugAndroidTest --stacktrace
