name: Boot Android Emulator

on: push

jobs:
  integration_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Android SDK components
        run: |
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --install 'platform-tools' 'emulator' 'system-images;android-29;default;x86_64'
          echo no | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/avdmanager create avd --force -n test -k 'system-images;android-29;default;x86_64' --device 'Nexus 6'

      - name: Remove old AVDs
        run: rm -rf ~/.android/avd/*

      - name: Install system image
        run: sdkmanager "system-images;android-29;default;x86_64"

      - name: Create AVD
        run: echo "no" | avdmanager create avd -n test -k "system-images;android-29;default;x86_64" --force

      - name: Start emulator
        run: |
         $ANDROID_HOME/emulator/emulator -avd test -no-window -no-audio -no-boot-anim -accel on &
         timeout 300 bash -c "until adb shell getprop sys.boot_completed | grep -m 1 '1'; do sleep 5; done"