name: Boot Android Emulator

on:
  push:
    branches: [ main ]

jobs:
  integration_test:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Install and run Appium
        run: |
          npm install -g appium@1.22
          appium --version
          appium &>/dev/null &

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          system-image-api-level: 34-ext9
          target: google_apis
          arch: x86_64
          emulator-options: -no-window
         script: mvn clean test -Pandroid