name: Android Instrumentation Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest  # Fastest for AVD boot

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Launch Pixel 3a Emulator & Run Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        target: google_apis
        arch: x86_64
        profile: pixel
        disable-animations: true
        emulator-options: "-no-snapshot-save -no-window -gpu swiftshader_indirect"
        script: |
          echo "Waiting for emulator to boot..."
          adb wait-for-device

          boot_completed=""
          until [[ "$boot_completed" == "1" ]]; do
            boot_completed=$(adb shell getprop sys.boot_completed | tr -d '\r')
            echo "Boot status: $boot_completed"
            sleep 5
          done

          echo "Emulator is ready! Starting tests..."
          ./gradlew connectedDebugAndroidTest --stacktrace