name: Launch Android Emulator

on:
  workflow_dispatch:

jobs:
  launch-emulator:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2

    - name: Install emulator
      run: |
        echo "y" | sdkmanager "platform-tools" "platforms;android-30" "emulator" "system-images;android-30;google_apis;x86_64"
        echo "y" | sdkmanager --licenses

    - name: Create AVD
      run: |
        echo "no" | avdmanager create avd -n testEmulator -k "system-images;android-30;google_apis;x86_64" --device "pixel"

    - name: Start Emulator
      run: |
        nohup emulator -avd testEmulator -no-window -no-audio -no-snapshot &
        adb wait-for-device

    - name: Wait for Boot
      run: |
        timeout 360s bash -c "until adb shell getprop sys.boot_completed | grep -m 1 '1'; do sleep 5; done"
        adb shell input keyevent 82