name: Android Emulator Boot Only

on: push

jobs:
  emulator-only:
    name: Android Emulator
    runs-on: macos-14

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Launch Emulator Only (Expecting emulator-5554)
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: arm64-v8a
          profile: emulator-5554
          disable-animations: true
          script: |
            echo "✅ Emulator booted."
            echo "Connected devices:"
            adb devices
            DEVICE_ID=$(adb devices | grep emulator | awk '{print $1}')
            echo "📱 ADB Device ID: $DEVICE_ID"
            if [[ "$DEVICE_ID" != "emulator-5554" ]]; then
              echo "❌ Emulator is not running as emulator-5554"
              exit 1
            else
              echo "✅ emulator-5554 is running as expected."
            fi
