name: Android Emulator

on: push
jobs:
  connected-tests:
    runs-on: macos-14  # ✅ Required for Apple Silicon runners

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'gradle'
        
      - name: Run connected tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: arm64-v8a     # ✅ Fix: ARM architecture for mac M1/M2
          profile: pixel_6    # ✅ ARM-friendly device
          disable-animations: true
          script: ./gradlew connectedCheck
        