name: Android Emulator Boot Only

on: push

jobs:
  emulator-only:
    runs-on: macos-14

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Launch Emulator
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
         api-level: 30
         target: google_apis
         arch: arm64-v8a           # ✅ Use ARM image for macOS-14 runners
         profile: pixel_6          # ✅ ARM64-compatible AVD profile
         disable-animations: true
         emulator-boot-timeout: 600
         script: echo " Emulator booted"
