name: Launch Emulator Only

on:
  workflow_dispatch:

jobs:
  launch-emulator:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Launch Pixel Emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        target: google_apis
        arch: x86_64
        profile: pixel
        avd-name: emulator-5554
        disable-animations: true
        script: |
          echo "Waiting for emulator to fully boot..."
          while [[ $(adb shell getprop sys.boot_completed | tr -d '\r') != "1" ]]; do
            echo "Still booting..."
            sleep 5
          done
          echo "Emulator booted successfully."

          echo "Sleeping 10 seconds before exiting..."
          sleep 10
          echo " Done. Emulator will shut down automatically."
