name: Boot Android Emulator

on:
  push:
    branches: [ main ]

jobs:
  integration_test:
    runs-on: macos-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Install and run Appium
        run: |
          npm install -g appium@1.22
          appium --version
          appium &>/dev/null &

      - name: Launch emulator and run Appium tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: mvn clean test -Pandroid
