name: Appium Android Emulator CI

on: push 

jobs:
  test:
    runs-on: macos-latest  

    timeout-minutes: 30

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Launch Emulator and Run Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        target: google_apis
        arch: x86_64
        profile: emulator-5554
        disable-animations: true
        emulator-boot-timeout: 600  
        working-directory: ./android
        script: |
          echo "Running connected tests..."
          ./gradlew connectedDebugAndroidTest --stacktrace

