name: Android Instrumentation Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest  # Fastest for AVD boot

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Run Instrumentation Tests on Emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        target: google_apis
        arch: x86_64
        profile: pixel
        disable-animations: true
        script: |
          ./gradlew connectedDebugAndroidTest --stacktrace