name: Run Appium Tests on Emulator

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Appium Test on Android Emulator
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Maven
        run: sudo apt-get install -y maven

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses and install emulator tools
        run: |
          yes | sdkmanager --licenses
          sdkmanager --install "platforms;android-30" "platform-tools" "system-images;android-30;google_apis;x86_64"
          echo "no" | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" --force
          emulator -avd test -no-window -no-audio -no-boot-anim -no-snapshot-save &
          sleep 5

      - name: Add ADB to PATH
        run: echo "${ANDROID_SDK_ROOT}/platform-tools" >> $GITHUB_PATH

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Appium and drivers
        run: |
          npm install -g appium
          appium driver install uiautomator2
          appium --base-path /wd/hub > appium.log 2>&1 &
          sleep 5

      - name: Run Appium Tests
        run: mvn clean test -Dsurefire.suiteXmlFiles=testng.xml

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/
